services:
  dlb-web-service:
    image: dlb-web-service:1.2.4
    ports:
      - 127.0.0.1:8089:8089
  dlb-web-client:
    image: httpd:2.4
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./dlb-web-client:/usr/local/apache2/htdocs
