# 1024 bits Base64 key used to generate JWT ACCESS TOKENS (use e.g. https://generate.plus/en/base64)
dlb_web_service_auth_native_jwt_access_token_secret=kN3CTRHieE4Kq9ryz1IoTwuqhOqg9udgEoILLxwa87Naj719CFOOKAltK12xA7K7+KbQJ9TsxJ9FIjWqJTsI4xUMc5/M6y3M3G11v4fbV2b+MJi3FUlHNO9ZRiM9ipr88CJccl4Dnf/BCh3tWoUmOi534lJCflqMN0WMSv8kXcM=

# 1024 bits Base64 key used to generate JWT REFRESH TOKENS (use e.g. https://generate.plus/en/base64)
dlb_web_service_auth_native_jwt_refresh_token_secret=FtFPQkm+W5EajTn5azjDflVx5uumCNC3t/K68FXOHxXmPg6DnGueQqoer2/BJzQvguaxLvTdJq4ZmGe0chPoQr0Sc6BdboBLYOzmyDKcNkFJobEEkRi/wTU1hXtIIFj50rdt9vl/Fzx+FC6vI1bos+zndffl1/EJ1bWmsyCJ1dU=

mariadb_root_password=password

keycloak_client_secret=**********
keycloak_admin_username=admin
keycloak_admin_password=admin
