# Run using: "docker compose -f compose-with-keycloak-dev.yml up" from the {GIT}/dialoguebranch/dlb-web/docker-compose/ folder

name: dlb-web-keycloak

services:

  ###########
  # MariaDB #
  ###########

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${mariadb_root_password}
    volumes:
      - mariadb:/var/lib/mysql
      - ./import/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  ##############
  # phpMyAdmin #
  ##############

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mariadb
    ports:
      - "8100:80"

  ###############################
  # Dialogue Branch Web Service #
  ###############################

  dlb-web-service:
    container_name: dlb-web-service
    image: dlb-web-service:dev
    ports:
      - 127.0.0.1:8089:8089
    volumes:
      - ../dlb-web-service/build/libs/dlb-web-service-1.2.5.war:/usr/local/tomcat/webapps/dlb-web-service.war

  ########################################
  # Keycloak Identity Management Service #
  ########################################

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${keycloak_admin_username}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${keycloak_admin_password}
      KC_DB: mariadb
      KC_DB_URL_HOST: mariadb
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: ${mariadb_root_password}
      KEYCLOAK_CLIENT_SECRET: ${keycloak_client_secret}
    entrypoint:
      - /bin/sh
      - -c
      - mkdir /opt/keycloak/data/import && sed -e "s/\(\"secret\"\s*:\s*\)\"[^\"]*\"/\1\"${KEYCLOAK_CLIENT_SECRET}\"/" /opt/keycloak/data/import-source/dialoguebranch-realm.json > /opt/keycloak/data/import/dialoguebranch-realm.json && /opt/keycloak/bin/kc.sh start-dev --import-realm
    volumes:
      - ./dlb-web/docker-compose/import/dialoguebranch-realm.json:/opt/keycloak/data/import-source/dialoguebranch-realm.json

networks:
  local_network:
    driver: bridge

volumes:
  mariadb:
