# Run using: "docker compose -f compose-with-keycloak-dev.yml up" from the {GIT}/dialoguebranch/dlb-web/docker-compose/ folder

name: dlb-web-service-keycloak-dev

services:

  ###############################
  # MariaDB #
  ###############################

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - mariadb:/var/lib/mysql
      - ./import/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  ###############################
  # Dialogue Branch Web Service #
  ###############################

  dlb-web-service:
    container_name: dlb-web-service
    image: dlb-web-service:dev
    ports:
      - 127.0.0.1:8089:8089
    volumes:
      - ../dlb-web-service/build/libs/dlb-web-service-1.2.5.war:/usr/local/tomcat/webapps/dlb-web-service.war

  ##############################
  # Dialogue Branch Web Client #
  ##############################

  #dlb-web-client:
  #  container_name: dlb-web-client
  #  image: httpd:2.4
  #  ports:
  #    - 127.0.0.1:8080:80
  #  volumes:
  #    - ../dlb-web-client:/usr/local/apache2/htdocs

  ########################################
  # Keycloak Identity Management Service #
  ########################################

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin 
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_URL_HOST: mariadb
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
    command: 
      - start-dev 
      - --import-realm
    volumes:
      - ./import/dialoguebranch-realm.json:/opt/keycloak/data/import/dialoguebranch-realm.json

networks:
  local_network:
    driver: bridge

volumes:
  mariadb:

