# Run using: "docker compose -f compose-with-keycloak.yml up" from the {GIT}/dialoguebranch/dlb-web/docker-compose/ folder

name: dlb-web-service-keycloak

services:

  ###############################
  # Dialogue Branch Web Service #
  ###############################

  dlb-web-service:
    container_name: dlb-web-service
    image: dlb-web-service
    ports:
      - 127.0.0.1:8089:8089

  ##############################
  # Dialogue Branch Web Client #
  ##############################

  #dlb-web-client:
  #  container_name: dlb-web-client
  #  image: httpd:2.4
  #  ports:
  #    - 127.0.0.1:8080:80
  #  volumes:
  #    - ../dlb-web-client:/usr/local/apache2/htdocs

  ########################################
  # Keycloak Identity Management Service #
  ########################################

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin 
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: 
      - start-dev 
      - --import-realm
    volumes:
      - ./import/dialoguebranch-realm.json:/opt/keycloak/data/import/dialoguebranch-realm.json

networks:
  local_network:
    driver: bridge