###############################
##### Basic Configuration #####
###############################

# This is the URL under which your Dialogue Branch External Variable Service will be reachable
dlb-configBaseUrl=http://localhost:8089/dlb-external-var-service

# The local directory used as data storage
dlb-configDataDir=/usr/local/dialogue-branch/data/dlb-external-var-service/

########################################
##### Authentication Configuration #####
########################################

# authService can be one of "keycloak", or "native"
dlb-configAuthService=native

dlb-configAuthKeycloakBaseUrl=http://keycloak:8080/
dlb-configAuthKeycloakRealm=dialoguebranch
dlb-configAuthKeycloakClientId=dlb-web-service
dlb-configAuthKeycloakClientSecret=**********

dlb-configAuthNativeAccessTokenExpirationSeconds=7200
dlb-configAuthNativeRefreshTokenExpirationSeconds=36000
dlb-configAuthNativeServiceUser=dlb-web-service
dlb-configAuthNativeServicePassword=dlb-web-service

# 1024 bits Base64 key used to generate JWTs (use e.g. https://generate.plus/en/base64)
dlb-configAuthNativeJwtAccessTokenSecret=Wpn3msAAxKoLvvvUUkq6W1aojsekf9FMhCFX+Ugkhhi8WZSL5BHrSOnxRM3ETIL/gmgknBzk/byvTZeSYkRQqCtPRi/C6gg71rprzim8gyRRT5P6ftdxIKotBz4/fqYkk7NECdN5WmCa0RXrYmWqh/PqBIqY57Jr19tr3mj7yuo=
dlb-configAuthNativeJwtRefreshTokenSecret=CYP3xzb67BXTkjYL8wgypVclucn4RrXJTYfl79U60IEEC4pWx2/mpi6IKjamT/XrKXUyrUiqXgG2eUK9/9QPcu78E0LQxwemUraTyFbJ4HAl/WsTWjwaOAq8ixa83mH6MpgtguNNLlAV14AK3NKoYyseKuCNitC5gj67IevXX5w=

###############################
##### Build configuration #####
###############################

# Set to "env" to disable compiling Javadoc and sources for a faster build
buildEnv=

################################
##### Gradle Configuration #####
################################

org.gradle.configuration-cache=true